apiVersion: v1
kind: Service
metadata:
  name: trendyrags-mssql
  labels:
    app: trendyrags
spec:
  ports:
    - port: 3306
  selector:
    app: trendyrags
    tier: mssql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  labels:
    app: trendyrags
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendyrags-mssql
  labels:
    app: trendyrags
spec:
  selector:
    matchLabels:
      app: trendyrags
      tier: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trendyrags
        tier: mssql
    spec:
      containers:
      - image: trendyrags.azurecr.io/trendyragsdb:latest
        name: mssql
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sa-pass
              key: password
        ports:
        - containerPort: 1433
          name: mssql
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: C:\data
      volumes:
      - name: mssql-persistent-storage
        hostPath:
          path: C:\database
          type: DirectoryOrCreate
# Currently, Azure disk is not accessible on Windows pod. Investigation needs.
#        persistentVolumeClaim:
#          claimName: mssql-pv-claim
